kind: Service
apiVersion: v1
metadata:
  name: authentication-srv
spec:
  selector:
    app: cardlesscash
    microservice: authentication
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP