apiVersion: apps/v1
kind: Deployment
metadata:
  name: tx-dep
spec:
  # Defines which pods are managed by this deployment.
  selector:
  # Defines the labels to match to select pods which are to be managed. Must match the labels on pods!
    matchLabels:
      app: cardlesscash
      microservice: transaction
   # Defines how many copies of each pod do we want
  replicas: 1
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: cardlesscash
        microservice: transaction
    spec:
      containers:
        - name: transaction-microservice
          # this must be from image repo
          image: "au.icr.io/cardlesscash-ns/transaction-microservice:11"
          ports:
            - name: http
              containerPort: 8083