kind: Service
apiVersion: v1
metadata:
  name: tx-srv
spec:
  selector:
    app: cardlesscash
    microservice: transaction
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
  type: ClusterIP